In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

retail_df = pd.read_csv('retail_prices.csv', parse_dates=['date'])
cpi_df = pd.read_csv('cpi.csv', parse_dates=['date'])

display(retail_df.head(2))
display(cpi_df.head(2))

        date      food_type sub_category                   commodity  price
0 2020-01-01  Calorie-Dense      Cereals  RICE, REGULAR-MILLED, 1 KG  35.80
1 2020-02-01  Calorie-Dense      Cereals  RICE, REGULAR-MILLED, 1 KG  35.92

        date income_group food_type sub_category    cpi
0 2020-01-01   All Income  Baseline    ALL ITEMS  103.9
1 2020-02-01   All Income  Baseline    ALL ITEMS  103.4